### ISSUE TITLE
Unable to run Carrier

### ISSUE THREAD

**Issue by Andrey-Demidovich** [carrier-io/carrier-io#16]
I've stacked at the step when Carrier is about to start (step 4 in localhost:9999).
Trace starts from Werkzeug package, so I suppose it is linked with the previously opened issue.

**Trace in Carrier site:**
Compiling Installation Configuration ... 
Installation Configuration Done, Preparing Containers ...

**Terminal trace:**
172.17.0.1 - - [04/Feb/2020 12:15:14] "GET /response HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0rc1-py3.6.egg/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0rc1-py3.6.egg/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0rc1-py3.6.egg/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0rc1-py3.6.egg/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 181, in install
    for line in self.compose_build():
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 118, in compose_build
    for line in self._popen_yield(cmd):
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 103, in _popen_yield
    raise CalledProcessError(return_code, cmd, popen.stderr.read())
subprocess.CalledProcessError: Command '['docker-compose', 'build']' returned non-zero exit status 1.

**Comment by arozumenko** [comment]
@Andrey-Demidovich issues are not linked. please provide:
1. Command you used to start container
2.Inputs you made prior to this step

**Comment by Andrey-Demidovich** [comment]
> 
> 
> @Andrey-Demidovich issues are not linked. please provide:
> 
>     1. Command you used to start container
>        2.Inputs you made prior to this step

I started with: docker run -it --rm -p 9999:9999 -v /tmp/carrier://opt/carrier -v //var/run/docker.sock://var/run/docker.sock getcarrier/carrier-io:latest

Prior this step I put a localhost as IP address, 2 parallel tasks and "Preload Jmeter" at step1 and localhost as Grafana and InfluxDB IPs at step 2.

**Comment by arozumenko** [comment]
could you please try to put IP address, which is reachable from outside of your local machine, not localhost (as it is DNS), not 127.0.0.1, but the IP which you have on your NIC.

for ubuntu type `ifconfig` that should help to find out proper set of digits and dots

**Comment by Andrey-Demidovich** [comment]
> 
> 
> could you please try to put IP address, which is reachable from outside of your local machine, not localhost (as it is DNS), not 127.0.0.1, but the IP which you have on your NIC.
> 
> for ubuntu type `ifconfig` that should help to find out proper set of digits and dots

With the public IP it shows the same error in terminal and:
ERROR: 
7 matches found based on name: network carrier is ambiguous

in Carrier installation site.

**Comment by arozumenko** [comment]
Seems like the error is different. According to it you tried more than once without cleaning up after yourself.
Please run uninstall script to clean things up (it should work, wan't checked for a while)
in browser open `http://localhost:9999/uninstall` it should remove network, volumes, containers, etc.

then restart the installation using public IP

**Comment by Andrey-Demidovich** [comment]
Uninstall was succesfull:

Uninstalling containers ... 
Remove volumes ... 
Remove network ... 
You are all clean ... 

Now I'm trying to resolve "index out of range" in InfluxDB container.

 File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 133, in create_databases
    influx_container = self.client.containers.list(filters={"label": "carrier=influx"})[0]
IndexError: list index out of range

**Comment by arozumenko** [comment]
I think you messed up config on second step of installation
please check the video and replicate steps https://www.youtube.com/watch?v=lX_SipWgP5E&list=PLPFS_qib3_6DNQZfR27oC4tMu5gJdZ0U1&index=2&t=108s

Please uninstall whatever you done first

**Comment by Andrey-Demidovich** [comment]
Nevermind, I've just deleted my own Grafana and InfluxDB in order to let Carrier install them from scratch.

Now it works. Thanks a lot.
