### ISSUE TITLE
Missing '/opt/carrier'

### ISSUE THREAD

**Issue by patuchov** [carrier-io/carrier-io#17]
I've been following the [QuickStart guide](https://github.com/carrier-io/carrier-io/wiki/Quick-Start) to install Carrier. 
After configuring instance and clicking **Done**, I'm getting the following error:

`Compiling Installation Configuration ... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 172, in install
    self.prepare_grafana()
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 60, in prepare_grafana
    mkdir(path.join(constants.WORKDIR, 'grafana'))
FileNotFoundError: [Errno 2] No such file or directory: '/opt/carrier/grafana'`

I need to create **/opt/carrier/** directory manually, in order to finish the configuration.

**Comment by arozumenko** [comment]
@patuchov this is not an expected behavior. Let me check how it can happen.

Could you please share the volumes you used while starting installation docker?

**Comment by patuchov** [comment]
I basically copy-pasted the command from QuickStart guide:

`docker run -it --rm -p 9999:9999 -v //var/run/docker.sock://var/run/docker.sock getcarrier/carrier-io:latest`

No additional volumes have been mounted.

**Comment by arozumenko** [comment]
that is actually the reason you've got an error. `-v <local folder for docker-compose>://opt/carrier` as in readme helps to avoid that

Anyway I fixed this within https://github.com/carrier-io/carrier-io/commit/6fa5fe52a1ca9d9034b05c008d92f0eefe657e53

**Comment by patuchov** [comment]
You should consider, updating the docs or redirect people to the README. Thanks for you help.
