### ISSUE TITLE
Allow override of Traefik default port

### ISSUE THREAD

**Issue by patuchov** [carrier-io/carrier-io#18]
On my server, port 8080 is already taken. This is causing Traefik container to fail while initial configuration phase. 
I would like to be able to override this setting.

**Comment by arozumenko** [comment]
@patuchov 
This is good one. Will be added in next build (in few hours)

**Comment by arozumenko** [comment]
Implemented, readme updated
https://github.com/carrier-io/carrier-io/commit/6fa5fe52a1ca9d9034b05c008d92f0eefe657e53
