### ISSUE TITLE
Notifications by email: Need parameter for FROM address different than smtp_user

### ISSUE THREAD

**Issue by jpfreeley** [carrier-io/carrier-io#35]
If using AWS SES to send an email notification, there needs to be a parameter for **FROM** address which differs from _smtp_user_. 

At this time, there isn't any "**FROM**" parameter documented, so I presume that one does not exist: https://github.com/carrier-io/carrier-io/wiki/Performance-Testing.-Notification-and-Alerting

**Comment by arozumenko** [comment]
Hi @jpfreeley 

You are right, it doesn't exists. You may add it through pull request to https://github.com/carrier-io/performance_email_notification repo or we will take care of it in few days (up to a week).

Thanks for reporting the case.
