### ISSUE TITLE
Test duration is short of what was specified

### ISSUE THREAD

**Issue by mtraneis** [carrier-io/carrier-io#36]
Since last Thursday (5/17) while running a series of tests on a version of our software we noticed that the test run suddenly gets cut short. We specified an hour but it only executed for 45 minutes.  We specified 2 hours duration but it only executed for 45 minutes.  About 37 minutes into the run the number of virtual users started to drop.  See  the screenshot below depicting JMeter throughput (for a 1 hour test run that was cut short).  Nothing changed in our code. We reviewed the logs of our code and did not find anything issues. Nothing is seen in the Jenkins log where we kicked off the carrier-io "build" or test run either.  Could there be something wrong with the load-generator? 

![image](https://user-images.githubusercontent.com/33640969/82457360-4eb37b00-9a83-11ea-9c12-38e2ba8760fe.png)

**Comment by arozumenko** [comment]
Hi @mtraneis is this behavior consistent? what the % of errors you are getting?

**Comment by mtraneis** [comment]
> Hi @mtraneis is this behavior consistent? what the % of errors you are getting?

Hi @arozumenko this behavior is consistent.  We're getting no errors at all

**Comment by arozumenko** [comment]
@mtraneis could you please share control-tower execution params? (pm or email should work)

**Comment by mtraneis** [comment]
There was an issue with the data file that the JMeter script uses that caused premature termination of the test run. After this issue was fixed the reported issue is resolved.  Thanks for helping to troubleshoot this problem.
