### ISSUE TITLE
Interpreting logging and deserialization time

### ISSUE THREAD

**Issue by mtraneis** [carrier-io/carrier-io#38]
This is not a bug or a carrier-io issue.  This is a question to the community and the carrier-io team to see if the following thought process is accurate. 

Our carrier-io instance reports a list of top slowest method calls and their total CPU time for the duration of the test run.
![image](https://user-images.githubusercontent.com/33640969/83038992-98fca500-a00b-11ea-923b-89bc34bb0cac.png).  

We're interested in knowing the percentage of total time the slow logging and JSON deserialization calls took.  There is no direct way to get to this number.  We were able to surmise or infer the value by the following calculations from the data that were available:

#1. Overall time of logging: 187459ms  (obtained from the figure above)
#2. Overall time of deserialization: 143351ms (obtained from the figure above)
#3. Total number of calls to both relevant methods for checkin and checkout: 44490  (obtained from JMeter chart)
 
Therefore
(A) Average time for logging is #1/#3  = 4.213ms 
(B) Average time for serialization and deserialization #2/#3 = 3.22ms 
 
#4. Checkout time: 1574ms ( a sum of relevant calls' time in the checkout workflow)
#5. Check in time: 1343ms ( a sum of relevant calls' time in the checkin workflow)
 
(C) percentage of checkout response time is A/#4x100 = 0.27% and B/#4x100 =0.205%, ~ 0.5%
(D) percentage of checkin response time is A/#5x100 = 0.24% and B/#5x100 = 0.24 -> ~0.5% 

Can this back-of-the-envelope calculation be taken seriously? Is it accurate, or is there another way, or a better way perhaps, to calculate the value for our inquiry?

A comment from our architect: "I think we are at the point where we need to look beyond the “top” slow function calls and look across the entire request time and categorize where that time is spent (as this is 99.5% of request time if your calculations hold). Can carrier.io generate a complete histogram?"

JMeter chart: 
![image](https://user-images.githubusercontent.com/33640969/83040369-2e4c6900-a00d-11ea-90ed-26bb371521de.png)

**Comment by arozumenko** [comment]
Hey @mtraneis can you give an example of complete histogram? based on that we can check if it is possible to do having your datasets.

**Comment by mtraneis** [comment]
> Hey @mtraneis can you give an example of complete histogram? based on that we can check if it is possible to do having your datasets.

@arozumenko Thanks for your response. What do you mean by a complete histogram? The JMeter chart or other charts?

**Comment by arozumenko** [comment]
Hi @mtraneis that was from your architect - "Can carrier.io generate a complete histogram?" what type of a histogram we are talking here? API to code mapping ?

**Comment by mtraneis** [comment]
Hi @arozumenko, I checked with him and he clarified that it was more of a loose term describing a breakdown of the time spent in each API call (which we already have).  These utility functions because they are called very frequently undoubtedly their total time would add up. We were trying to understand if we should optimize them. If it turns out that in the overall 1.5 seconds response time it only takes 0.5% of it, as my calculations show, then it's not worth optimizing. 
1) Could you please look over my calculations to see if the logic to derive the percentage of these logging time in the overall response time make sense because without having custom metrics to measure specific parts of the code it's hard to answer this question. 
2. If we had metrics that are either custom or exposed by the vertx or micrometer framework, could carrier-io capture them?

**Comment by mtraneis** [comment]
Hi @arozumenko Any thoughts or comments on the above inquiry?

**Comment by arozumenko** [comment]
Custom metrics can be logged to influx and visualized with Grafana. Nothing to do with carrier in particular.

The optimization priorities and logic you put behind calculations is better to discuss with your architects, as it is not related to carrier platform.
