### ISSUE TITLE
How to pass credentials to DAST zap for Basic HTTP authentication

### ISSUE THREAD

**Issue by Shukherberg** [carrier-io/carrier-io#45]
Hi,
I am trying to perform Dast zap scan on a web-site. But because I got basic HTTP authentication scan couldn't perform.
How do I pass credentials in config file for basic HTTP auth?

Thank you.

**Comment by arozumenko** [comment]
@Shukherberg  have you checked this one ? https://github.com/carrier-io/carrier-io/wiki/Security-Scanning.-DAST#authenticated-scanning

**Comment by Shukherberg** [comment]
Yes. I am a little confused which commands to use, I tried different options but seems like none of them worked. I pasted my website's URL in   - {command: open, target: 'https://target.example.com:443/', value: ''}
Also pasted creds values into auth_login and auth_password lines. Tried to run with "waitForElementPresent" commands an without them. I am not quite familiar with Selenium but I did some research in web and passing HTTP auth in Selenium looks a bit different.

**Comment by Shukherberg** [comment]
Also in docs it's looks more as for Sign in form, on a web-site. But basic HTTP auth comes before html is rendered.

**Comment by LifeDJIK** [comment]
Hi @Shukherberg,

At the moment we support only form-based authentication for ZAP (using selenium-like script).
We placed adding other supported types of authentication to our backlog - and will implement them in future.

**Comment by Shukherberg** [comment]
Thank you for answer
