### ISSUE TITLE
image is missing in the wiki

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/carrier-io#46]
seems like all the images in the WIKI is missing 

https://github.com/carrier-io/carrier-io/wiki/Performance-Testing.-Results-Analysis

![image](https://user-images.githubusercontent.com/3865402/91976758-6274ab80-ed19-11ea-856f-384ceb5fad13.png)

**Comment by hunkom** [comment]
I can see all the images.
<img width="981" alt="Screenshot 2020-09-02 at 15 19 18" src="https://user-images.githubusercontent.com/46744804/91980302-b094a980-ed2f-11ea-87c8-0e14fbb6bef7.png">

Did you try to open it in another browser?

**Comment by arozumenko** [comment]
@tokarthik does it require any other help?

**Comment by tokarthik** [comment]
no thanks it might be my browser issue
