### ISSUE TITLE
Lack of "document"/"help info" on perf report related WebGUI fields

### ISSUE THREAD

**Issue by webweb04** [carrier-io/carrier-io#48]
![image](https://user-images.githubusercontent.com/32888915/92671597-468c8d80-f349-11ea-8975-dae909ec639b.png)
I found that there is some field in the report UI that is not described in the github document, and I am not able to understand, would you like to show me the relevant document link ?

**Comment by arozumenko** [comment]
This could be addressed some time later in documents.
Documentation has low priority for now.
