### ISSUE TITLE
In report "95 PCT. RESP. TIME 97.0 Ms" should be "95 PCT. RESP. TIME 97.0 ms", customer may get confused, we may get challenged by customer for the "Ms"

### ISSUE THREAD

**Issue by webweb04** [carrier-io/carrier-io#49]
![image](https://user-images.githubusercontent.com/32888915/92671926-18f41400-f34a-11ea-9be9-590433b4bfc2.png)

https://public.getcarrier.io/report/backend?report_id=12

According to International Bureau of Weights and Measures stander https://www.bipm.org/en/measurement-units/prefixes.html

The Ms means mega second (1 000 000 sedond), not milli second (0.001 second)

This will make customer get confused and customer may lose some trust on us if we show interface with this "Ms" to customer.

Is's just a suggestion, would you like to change it to ms?

Thanks

**Comment by arozumenko** [comment]
![Screen Shot 2020-09-10 at 8 53 15 AM](https://user-images.githubusercontent.com/6542858/92687193-c44d9a80-f343-11ea-9b80-97b804b3ed49.png)
