### ISSUE TITLE
No test report when creating performance test with following steps

### ISSUE THREAD

**Issue by webweb04** [carrier-io/carrier-io#51]
When creating performance test with following steps (out.zip) with the following package (google.zip), it won't generate test report after execution.

Would you like to tell me why? and Would you like to tell me how to create new performance test inorder to make the test report get generated after the execution?

Test Name googleTestNewtest

![image](https://user-images.githubusercontent.com/32888915/92676418-0f6fa980-f354-11ea-9d9b-62ba09cef30f.png)

![image](https://user-images.githubusercontent.com/32888915/92676361-f666f880-f353-11ea-9e03-835e02dc96b3.png)

The screen capture steps, use the VLC player and ffmpeg to decode and playback, upload to Confluence may decode and playback too:
[out.zip](https://github.com/carrier-io/carrier-io/files/5198912/out.zip)

[google.zip](https://github.com/carrier-io/carrier-io/files/5198905/google.zip)

For existing test (test NAME: testGoogle) it was executed succesfully with test report generated, but after  I made modification on Parallel runners from 1 to 3,  but not working after I made this modification, and even I change it back, the test plan won't work anymore.

**Comment by webweb04** [comment]
For existing test (test NAME: testGoogle) it was executed succesfully with test report generated, but after I made modification on Parallel runners from 1 to 3, but not working after I made this modification, and even I change it back, the test plan won't work anymore.

**Comment by arozumenko** [comment]
That was because in between you spammed a queue with different tasks, they were misconfigured.
Please confirm test  works now

**Comment by webweb04** [comment]
fixed verified
