### ISSUE TITLE
[Suggestion] when DURATION less than 1 second, show in float value or show in ms would be better.

### ISSUE THREAD

**Issue by webweb04** [carrier-io/carrier-io#52]
![image](https://user-images.githubusercontent.com/32888915/92678362-68414100-f358-11ea-8cce-5ffd13cc18fa.png)

In the performance report, there is DURATION 0 S, that would be better if it is 
DURATION
0.025 S

or 

DURATION
25 ms

**Comment by webweb04** [comment]
DURATION is still 0 when actually the test duration lasts minutes 


![image](https://user-images.githubusercontent.com/32888915/93043656-16185c80-f685-11ea-998f-41a95f7396b9.png)

**Comment by hunkom** [comment]
Fixed
