### ISSUE TITLE
NO test report after execution DAST test (NAME:googleTestNewtest)

### ISSUE THREAD

**Issue by webweb04** [carrier-io/carrier-io#53]
A DAST test (NAME:googleTestNewtest  UUID:65964e29-1c51-4829-ac06-fd25292a1170) was created like this:

Then after execution, there is no test report

![image](https://user-images.githubusercontent.com/32888915/92681608-afcbcb00-f360-11ea-85c2-2d65f53dcc65.png)

The screen capture steps, use the VLC player and ffmpeg to decode and playback, upload to Confluence may decode and playback too:
[out.zip](https://github.com/carrier-io/carrier-io/files/5199166/out.zip)

**Comment by arozumenko** [comment]
Do you have any of Jira or SMTP configured?
Have you checked any other combinations of scanners?

**Comment by webweb04** [comment]
> Do you have any of Jira or SMTP configured?
> Have you checked any other combinations of scanners?

Hello,

Is that necessary to configure JIRA or SMTP  to see the online report ?

I didn't checked other combinations, what is the suggest combinations?

**Comment by arozumenko** [comment]
No it is not necessary.
The issue there is that you haven't configured non-default Redis password.
We may add it in future to be seamless, but currently you need to do it manually.

Please confirm DAST is working as expected

**Comment by webweb04** [comment]
fixed verified
