### ISSUE TITLE
incorrect statistics/reports in performance testing report sum of requests less than sum of reponse from begining

### ISSUE THREAD

**Issue by webweb04** [carrier-io/carrier-io#58]
Background : AS https REST API won't have multiple response on single request when the client doesn't follow redirect  (even if follows redirect, it is another request for the redirect)

AC1:
should not have less requests/hits than response from the begining in any case( except choose the TIME PICKER not from the real begining)

Actual behavior1 :    

For the Hits/TPS in OVERVIEW chart of the performance testing report

I have already selected "all" of the TIME PICKER, while for the second "09-11 05:42:59", total hits (total requests) from the begining to now is 1 less than the total response, it is NOT posible in reality since in the nature of https REST API won't have behavior like that, I can make sure it is a bug.

![requests (1)](https://user-images.githubusercontent.com/32888915/92877307-9a789e80-f43d-11ea-99df-3238e060c0cc.png)
![image](https://user-images.githubusercontent.com/32888915/92877399-b54b1300-f43d-11ea-9662-b80dac2d4fb8.png)

analysis (guess)1:

I think there is two possibilitys 
1, (much highers) the incorrect way to statistics jmeter raw testing logs, incorrect understand and useage of the fields and data in jmeter raw log.
2, (less possibility) the begining point is incorrectly choosen.
There would be also other possibilitys, I think developers could check, and would you like to provide me the steps to obtain jmeter raw testing log from the backend? so I can do futhure invegesting, Thanks.

AC2:
should not have less requests/hits than response from the begining in any case( except choose the TIME PICKER not from the real begining)

Actual behavior2:    
Analytics  in OVERVIEW chart of the performance testing report

I have already selected "all" of the TIME PICKER, while for the second "09-11 05:42:35"(first second), total hits (total requests) from the begining to now is 3 less than the total response, it is NOT posible in reality since in the nature of https REST API won't have behavior like that, I can make sure it is a bug.

![image](https://user-images.githubusercontent.com/32888915/92878932-24753700-f43f-11ea-8d46-8b2ed6f3cee1.png)
![analytics (1)](https://user-images.githubusercontent.com/32888915/92878950-27702780-f43f-11ea-9acb-9d73135d6481.png)

analysis (guess)2:
same as analysis (guess)1:

**Comment by webweb04** [comment]
[google.zip](https://github.com/carrier-io/carrier-io/files/5207226/google.zip)
The test

**Comment by arozumenko** [comment]
this is specifics of aggregation based on first response.
there are cases when hit can go outside of the time range and won't be present
it happened only for first aggregation interval, so barely a problem.

Won't fix for now
