### ISSUE TITLE
not able to run via Jenkins pipeline

### ISSUE THREAD

**Issue by tokarthik** [carrier-io/carrier-io#64]
i have try to run via pipeline from external Jenkins 
`docker run -e project_id=1 -e galloper_url=http://carrier-mysite.com -e token=XXXXXX getcarrier/control_tower:latest --test_id=5bb0e46b-0788-406e-933b-8abc78b06ec6`

is there any documentation on how to do it

**Comment by tokarthik** [comment]
is there any galloper API which I can call for to run the test

**Comment by hunkom** [comment]
@tokarthik the command looks right. Could you share logs from control_tower container in Jenkins?

**Comment by tokarthik** [comment]
have fixed the docker permission issue using the below command , I am sharing here it will be useful for others `sudo groupadd docker
sudo usermod -aG docker $USER`
Run the following command or Logout and login again and run (that doesn't work you may need to reboot your machine first)
`$ newgrp docker

`
@hunkom this is the error 
![image](https://user-images.githubusercontent.com/3865402/97453453-a8bb4500-192d-11eb-868f-a91eb534128b.png)

**Comment by hunkom** [comment]
The error occurs after test execution, when control-tower container is trying to process jUnit report. Seems like you have to mount Jenkins workspace to the container. By default, jUnit report is saved in /tmp/reports directory in the control tower container.

**Comment by tokarthik** [comment]
i am trying to mount 

`
pipeline {
    
    agent { label 'Jenkins-Slave-2' }
    
	stages{
	    
	    stage("Env Variables") {
            steps {
                sh "printenv"
            }
        }
    stage('Tests') {
			parallel {
				stage('Regression') {
					steps {
						echo "Assuming good"
					}
				}
				stage('Performance') {
					steps {
						script {
							def dockerParamsString = "--entrypoint=''"
							def params = [
								"-t",
								"-e project_id=1",
								"-e galloper_url=http://xxxx.carrier.net",
								"-e token=-ZPCMkYaBBEIiaOyyQsmKBDD1eQ3Kjy1c",
								"-v ${env.WORKSPACE}/:/tmp/reports/:rw"
							
							]
							for (param in params) {
								dockerParamsString += " ${param}"
							}
							echo "${env.WORKSPACE}"
                            docker.image("getcarrier/control_tower:latest").inside(dockerParamsString){
                                echo "Starting job"
                                sh """run --test_id=5bb0e46b-0788-406e-933b-8abc78b06ec6 -p ${env.WORKSPACE}/reports"""
                            }
						}
					}
				}
            }}
    }

}`

![image](https://user-images.githubusercontent.com/3865402/97471574-c7770700-1940-11eb-922a-8cccce82c125.png)

**Comment by hunkom** [comment]
Did you cancel the test from galloper? If so, did you click **Cancel** button on the reports page or **Trigger post processing** button? From the control-tower logs I can see that "Test was canceled".

**Comment by tokarthik** [comment]
Tried the below code and worked  but the JUNIT file created with no reuslt

`
pipeline {
    
    agent { label 'Jenkins-Slave-2' }
    
	stages{
	    
	    stage("Env Variables") {
            steps {
                sh "printenv"
            }
        }
    stage('Tests') {
			parallel {
				stage('Regression') {
					steps {
						echo "Assuming good"
					}
				}
				stage('Performance') {
					steps {
						script {
							def dockerParamsString = "--entrypoint=''"
							def params = [
							    "-t",
								"-e project_id=1",
								"-e galloper_url=http://carrier.taasmeter.net",
								"-e token="XXXXXX",
								"-v ${env.WORKSPACE}/:/tmp/reports/:rw"
							]
							for (param in params) {
								dockerParamsString += " ${param}"
							}
							echo "${env.WORKSPACE}"
                            docker.image("getcarrier/control_tower:latest").inside("${dockerParamsString}"){
                                echo "Starting job"
                                sh """/usr/local/bin/run --test_id 5bb0e46b-0788-406e-933b-8abc78b06ec6"""
                            }
						}
					}
				}
				
            }}
    }
    post {
        always {
            step([$class: 'JUnitResultArchiver', testResults: '*.xml', healthScaleFactor: 1.0])
            publishHTML (target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'coverage',
                    reportFiles: 'index.html',
                    reportName: "Junit Report"
            ])
        }
    }

}`

Seems like an issue with JUnit report creation 
![image](https://user-images.githubusercontent.com/3865402/97501618-7d564b80-1969-11eb-80f6-8418a7886102.png)

**Comment by tokarthik** [comment]
![image](https://user-images.githubusercontent.com/3865402/97501679-9ced7400-1969-11eb-85a8-12f6e07b5d6a.png)

**Comment by tokarthik** [comment]
@hunkom is there any settings we need to do get the junit test report

**Comment by hunkom** [comment]
@tokarthik jUnit report is created based on thresholds. You can set thresholds for each test in Galloper. 
<img width="704" alt="Screenshot 2020-10-29 at 13 20 35" src="https://user-images.githubusercontent.com/46744804/97561918-8b4bb100-19e9-11eb-9a08-ab3f2a4768f0.png">

**Comment by tokarthik** [comment]
got it thanks

**Comment by tokarthik** [comment]
I will setup and test it
thanks @hunkom

**Comment by tokarthik** [comment]
working fine thanks @hunkom
